import { Tool, Category } from './types';

export const CATEGORIES: Category[] = [
  '全部',
  'AI工具',
  'PPT演示',
  '设计美化',
  '视频剪辑',
  '音频处理',
  '办公效率',
];

export const TOOLS: Tool[] = [
  {
    id: 'ai-chat-1',
    title: 'DeepSeek (深度求索)',
    description: '国产最强开源模型，写教案、写总结逻辑非常强，完全免费且中文理解能力极佳。',
    url: 'https://chat.deepseek.com/',
    category: 'AI工具',
    subcategory: '对话模型',
    tags: ['AI对话模型', '教案生成', '直连可用'],
    featured: true,
  },
  {
    id: 'ai-tool-notebook',
    title: 'NotebookLM',
    description: '谷歌最强笔记AI。把几万字的PDF教材、文献扔进去，它能瞬间学会并回答你的所有问题，还能生成播客讨论。',
    url: 'https://notebooklm.google.com/',
    category: 'AI工具',
    subcategory: '对话模型',
    tags: ['AI对话模型', '笔记', '总结', 'Google', '网络受限'],
    featured: true,
  },
  {
    id: 'ai-chat-2',
    title: '文心一言',
    description: '百度的AI助手，适合查找中文资料、润色文章，由于是国内访问速度最快。',
    url: 'https://yiyan.baidu.com/',
    category: 'AI工具',
    subcategory: '对话模型',
    tags: ['AI对话模型', '百度', '直连可用'],
  },
  {
    id: 'ai-chat-6',
    title: '讯飞星火',
    description: '科大讯飞出品的AI，尤其擅长公文写作、教育教学场景的对话，语音识别能力很强。',
    url: 'https://xinghuo.xfyun.cn/desk',
    category: 'AI工具',
    subcategory: '对话模型',
    tags: ['AI对话模型', '写作', '直连可用'],
  },
  {
    id: 'ai-chat-3',
    title: 'Google Gemini',
    description: '谷歌的AI助手，擅长多模态（识别图片内容），逻辑推理能力强，响应速度快。',
    url: 'https://gemini.google.com/',
    category: 'AI工具',
    subcategory: '对话模型',
    tags: ['AI对话模型', 'Google', '网络受限'],
    featured: true,
  },
  {
    id: 'ai-chat-4',
    title: 'Claude 3',
    description: '非常拟人化的AI，写出来的文章很有“人味”，不做作，适合写发言稿或信件。',
    url: 'https://claude.ai/',
    category: 'AI工具',
    subcategory: '对话模型',
    tags: ['AI对话模型', '写作', '网络受限'],
    featured: true,
  },
  {
    id: 'ai-chat-5',
    title: 'Grok (xAI)',
    description: '马斯克旗下的AI，由于连接了X(推特)，对实时新闻和热点事件了解非常迅速。',
    url: 'https://x.com/i/grok',
    category: 'AI工具',
    subcategory: '对话模型',
    tags: ['AI对话模型', '实时', '网络受限'],
  },
  {
    id: 'ai-chat-7',
    title: 'Perplexity',
    description: '结合了搜索引擎的AI，回答问题时会给出真实引用来源，适合查证资料、做学术研究。',
    url: 'https://www.perplexity.ai/',
    category: 'AI工具',
    subcategory: '对话模型',
    tags: ['AI搜索', 'AI对话模型', '学术', '网络受限'],
  },
  {
    id: 'ai-chat-8',
    title: 'HuggingChat',
    description: 'HuggingFace推出的开源AI对话助手，可以免费体验各种最新的开源大模型。',
    url: 'https://huggingface.co/chat/',
    category: 'AI工具',
    subcategory: '对话模型',
    tags: ['AI对话模型', '开源', '网络受限'],
  },
  {
    id: 'ai-video-kling',
    title: '可灵 AI (Kling)',
    description: '快手推出的视频生成大模型，效果震撼，支持文生视频、图生视频，不仅画质清晰，动作幅度也很大。',
    url: 'https://app.klingai.com/cn/',
    category: 'AI工具',
    subcategory: '视频生成',
    tags: ['AI视频生成', '快手', '直连可用'],
  },
  {
    id: 'ai-video-runway',
    title: 'RunwayML',
    description: '好莱坞级别的AI视频生成工具。输入文字即可生成视频，还支持视频抠图、魔法消除背景等黑科技。',
    url: 'https://runwayml.com/',
    category: 'AI工具',
    subcategory: '视频生成',
    tags: ['AI视频生成', '特效', '网络受限'],
  },
  {
    id: 'ai-video-hedra',
    title: 'Hedra',
    description: '专注于人物视频生成的AI。上传一张照片和一段音频，它能生成表情生动、口型精准的说话/唱歌视频。',
    url: 'https://www.hedra.com/app/home',
    category: 'AI工具',
    subcategory: '视频生成',
    tags: ['AI视频生成', '数字人', '网络受限'],
  },
  {
    id: 'ai-img-4',
    title: '即梦 (Jimeng)',
    description: '字节跳动出品的AI创作平台，不仅能画图，还能把图片变成视频，效果非常惊艳。',
    url: 'https://jimeng.jianying.com/ai-tool/home/',
    category: 'AI工具',
    subcategory: '视频生成',
    tags: ['AI视频生成', '绘画', '字节', '直连可用'],
  },
  {
    id: 'ai-video-heygen',
    title: 'HeyGen (数字人)',
    description: '顶级的AI数字人工具。上传一张照片和一段文字，就能生成嘴型自然、表情生动的讲解视频，适合做微课助教。',
    url: 'https://www.heygen.com/',
    category: 'AI工具',
    subcategory: '数字人',
    tags: ['AI数字人', '微课', '生成', '网络受限'],
  },
  {
    id: 'ai-video-did',
    title: 'D-ID',
    description: '让静态照片“开口说话”。非常适合历史课（让历史人物“复活”自我介绍）或语文课的情境导入。',
    url: 'https://www.d-id.com/',
    category: 'AI工具',
    subcategory: '数字人',
    tags: ['AI数字人', '照片说话', '教学', '网络受限'],
  },
  {
    id: 'ai-video-vrew',
    title: 'Vrew',
    description: '像编辑Word文档一样剪辑视频。它能自动识别视频里的语音生成字幕，删掉字幕文本就等于剪掉了对应的视频片段。',
    url: 'https://vrew.voyagerx.com/',
    category: 'AI工具',
    subcategory: '视频剪辑',
    tags: ['AI视频剪辑', '字幕', '效率', '网络受限'],
    featured: true,
  },
  {
    id: 'ai-audio-ttsmaker',
    title: 'TTSMaker (马克配音)',
    description: '永久免费的文本转语音工具。支持中文、英文等多种语言，有多种逼真的主播音色，做课件配音首选。',
    url: 'https://ttsmaker.com/zh-cn',
    category: 'AI工具',
    subcategory: '音频处理',
    tags: ['AI配音', '免费', '语音', '直连可用'],
  },
  {
    id: 'ai-audio-11labs',
    title: 'ElevenLabs',
    description: '目前全球效果最逼真的AI语音生成，情绪表达非常自然，几乎听不出是机器。适合制作英语听力素材。',
    url: 'https://elevenlabs.io/',
    category: 'AI工具',
    subcategory: '音频处理',
    tags: ['AI配音', '英语', '网络受限'],
  },
  {
    id: 'ai-img-1',
    title: 'Midjourney',
    description: '目前全球效果最好的AI绘画工具。输入文字即可生成极具艺术感的图片，适合做独特的课件插图。',
    url: 'https://www.midjourney.com/',
    category: 'AI工具',
    subcategory: '绘画设计',
    tags: ['AI绘画', '设计', '网络受限'],
    featured: true,
  },
  {
    id: 'ai-img-3',
    title: 'LiblibAI (哩布哩布)',
    description: '国内最大的AI绘画模型分享站，也提供在线生图功能，有很多适合中国审美的国风模型。',
    url: 'https://www.liblib.art/',
    category: 'AI工具',
    subcategory: '绘画设计',
    tags: ['AI绘画', '模型', '直连可用'],
  },
  {
    id: 'ai-img-2',
    title: 'BigJPG',
    description: 'AI无损放大图片。网上找的素材图片太小、模糊？用它放大后依然清晰，不失真。',
    url: 'https://bigjpg.com/',
    category: 'AI工具',
    subcategory: '绘画设计',
    tags: ['图片放大', '修复', '直连可用'],
    featured: true,
  },
  {
    id: 'ai-platform-hf',
    title: 'Hugging Face (抱抱脸)',
    description: '全球最大的AI开源社区，被誉为“AI界的GitHub”。这里汇聚了海量的开源模型、数据集和在线体验Demo。',
    url: 'https://huggingface.co/',
    category: 'AI工具',
    subcategory: '效率工具',
    tags: ['开源社区', '模型库', '网络受限'],
    featured: true,
  },
  {
    id: 'ai-tool-1',
    title: 'YouMind',
    description: 'AI驱动的思维导图工具。输入一个主题，自动帮你生成完整的思维导图框架，备课神器。',
    url: 'https://youmind.com/boards/new',
    category: 'AI工具',
    subcategory: '效率工具',
    tags: ['思维导图', 'AI脑暴', '网络受限'],
  },
  {
    id: 'ai-tool-2',
    title: 'Stable Audio',
    description: 'AI音乐生成工具。输入描述词（如“欢快的钢琴曲”），自动生成无版权风险的背景音乐。',
    url: 'https://stableaudio.com/generate',
    category: 'AI工具',
    subcategory: '音频处理',
    tags: ['AI音乐', '生成', '网络受限'],
    featured: true,
  },
  {
    id: 'ai-tool-4',
    title: '通义听悟',
    description: '阿里推出的AI会议转写工具。支持实时录音转文字、音视频文件转文字，还能自动生成总结和思维导图，非常适合整理教研会议记录。',
    url: 'https://tingwu.aliyun.com/',
    category: 'AI工具',
    subcategory: '效率工具',
    tags: ['转写', '会议', '效率', '直连可用'],
    featured: true,
  },
  {
    id: 'ppt-slidesgo',
    title: 'Slidesgo',
    description: '我最喜欢的PPT模板网站！设计感极强，风格国际化，每一套都堪比艺术品。',
    url: 'https://slidesgo.com/',
    category: 'PPT演示',
    tags: ['模板', '设计', '网络受限'],
    featured: true,
  },
  {
    id: 'ppt-1',
    title: 'iSlide插件',
    description: 'PPT必备神器！有一键排版、海量图标库，做课件效率提升10倍。',
    url: 'https://www.islide.cc/',
    category: 'PPT演示',
    tags: ['插件', '排版', '效率', '直连可用'],
    featured: true,
  },
  {
    id: 'ppt-4',
    title: 'PDF24 Tools',
    description: '德国的老牌PDF工具箱，完全免费且无广告，支持PDF编辑、合并、压缩等所有功能。',
    url: 'https://tools.pdf24.org/zh/',
    category: 'PPT演示',
    tags: ['PDF', '工具箱', '免费', '直连可用'],
    featured: true,
  },
  {
    id: 'ppt-6',
    title: 'Kimi 智能助手',
    description: '超长文本分析神器。把几十页的教案或文献扔给它，快速帮你总结重点，做PPT大纲的神辅助。',
    url: 'https://www.kimi.com/',
    category: 'PPT演示',
    tags: ['AI辅助', '总结', '大纲', '直连可用'],
  },
  {
    id: 'design-1',
    title: 'Canva 可画',
    description: '零基础设计神器。班级奖状、活动海报、邀请函、公众号封面一键套用模板。',
    url: 'https://www.canva.cn/',
    category: '设计美化',
    tags: ['海报', '奖状', '设计', '直连可用'],
    featured: true,
  },
  {
    id: 'design-5',
    title: 'Yandex Images',
    description: '俄罗斯的搜索引擎，以图搜图功能极其强大。找不到高清原图时用它搜，效果往往比百度谷歌都好。',
    url: 'https://yandex.com/images/',
    category: '设计美化',
    tags: ['搜图', '高清', '直连可用'],
    featured: true,
  },
  {
    id: 'design-7',
    title: '花瓣网',
    description: '寻找设计灵感的地方。做黑板报、班级布置没有思路？来这里搜一搜，全是美图。',
    url: 'https://huaban.com/',
    category: '设计美化',
    tags: ['灵感', '美图', '直连可用'],
    featured: true,
  },
  {
    id: 'design-8',
    title: 'ffflux',
    description: '极简风格的动态背景生成器，可以生成非常高级的流体波浪背景图，用在PPT里很显档次。',
    url: 'https://www.fffuel.co/ffflux/',
    category: '设计美化',
    tags: ['背景', '生成器', 'SVG', '直连可用'],
    featured: true,
  },
  {
    id: 'design-9',
    title: 'Iconfont 阿里图标库',
    description: '阿里巴巴出品的矢量图标库，PPT里需要用到的小图标、小符号，这里应有尽有。',
    url: 'https://www.iconfont.cn/',
    category: '设计美化',
    tags: ['图标', '素材', '阿里', '直连可用'],
    featured: true,
  },
  {
    id: 'video-1',
    title: '剪映电脑版',
    description: '最适合老师的视频剪辑软件。自动识别字幕，海量片头片尾素材，做微课首选。',
    url: 'https://lv.ulikecam.com/',
    category: '视频剪辑',
    tags: ['剪辑', '微课', '字幕', '直连可用'],
  },
  {
    id: 'video-4',
    title: 'LookAE (大众脸)',
    description: '专业的视频制作资源站，有海量的PR/AE插件、模板和教程，适合想要进阶学习视频制作的老师。',
    url: 'https://www.lookae.com/',
    category: '视频剪辑',
    tags: ['插件', '资源', '进阶', '直连可用'],
    featured: true,
  },
  {
    id: 'video-6',
    title: 'Jijidown (唧唧)',
    description: 'B站视频下载工具。看到好的教学视频想下载到电脑上放？把链接复制进去就能下载。',
    url: 'http://client.jijidown.com/',
    category: '视频剪辑',
    tags: ['下载', 'B站', '工具', '直连可用'],
    featured: true,
  },
  {
    id: 'audio-1',
    title: 'Vocal Remover',
    description: '人声伴奏一键分离。演出找不到伴奏？上传原曲，自动把人声消除，保留伴奏。',
    url: 'https://vocalremover.org/ch/',
    category: '音频处理',
    tags: ['伴奏', '消音', '分离', '直连可用'],
    featured: true,
  },
  {
    id: 'audio-4',
    title: 'UVR5 音频分离 (52破解)',
    description: '【硬核工具】比网页版更强大的人声分离软件。如果对伴奏质量要求极高，建议下载这个软件。',
    url: 'https://www.52pojie.cn/thread-2014819-1-1.html',
    category: '音频处理',
    tags: ['软件', '专业', '伴奏', '直连可用'],
    featured: true,
  },
  {
    id: 'audio-3',
    title: 'Unlock Music (音乐解锁)',
    description: '专治各种音乐格式不兼容。网易云/QQ音乐下载的加密格式（如ncm），拖进去就能变成普通的mp3。',
    url: 'https://demo.unlock-music.dev/',
    category: '音频处理',
    tags: ['解密', '格式转换', '工具', '直连可用'],
    featured: true,
  },
  {
    id: 'eff-6',
    title: 'LocalSend',
    description: '局域网互传神器。手机传照片到电脑、电脑传文件给同事，不用登录微信，速度极快。',
    url: 'https://localsend.org/zh-CN',
    category: '办公效率',
    tags: ['传输', '文件', '工具', '直连可用'],
    featured: true,
  },
  {
    id: 'eff-1',
    title: 'Everything',
    description: '电脑文件秒搜工具。找教案、找学生名单，输入名字瞬间找到，比系统自带快无数倍。',
    url: 'https://www.voidtools.com/zh-cn/',
    category: '办公效率',
    tags: ['搜索', '文件', '直连可用'],
  },
  {
    id: 'eff-3',
    title: '草料二维码',
    description: '快速生成二维码。把问卷链接、视频地址变成二维码，方便打印在通知单上。',
    url: 'https://cli.im/',
    category: '办公效率',
    tags: ['二维码', '工具', '直连可用'],
  },
  {
    id: 'eff-7',
    title: '格式工厂 (FormatFactory)',
    description: '万能格式转换软件。视频打不开？音频格式不对？用它转一下，支持几乎所有格式。',
    url: 'http://www.pcfreetime.com/formatfactory/cn/index.html',
    category: '办公效率',
    tags: ['转换', '软件', '老牌', '直连可用'],
    featured: true,
  },
  {
    id: 'eff-4',
    title: 'Notion',
    description: '全能的笔记与知识管理工具。可以用来整理教案库、班级管理日志，界面非常美观灵活。',
    url: 'https://www.notion.so/',
    category: '办公效率',
    tags: ['笔记', '管理', '协作', '直连可用'],
    featured: true,
  },
];